#FROM apache/airflow:2.3.4-python3.7
FROM airflow_scheduler_tgs
#ADD python-project-390907-11f79da5c0ca.json /opt/airflow/dags

#USER user
RUN pip install selenium && \
    pip install bs4 && \
    pip install lxml && \
    pip install pip install gspread && \
    pip install pip install oauth2client && \
    pip install selenium-stealth